version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ../../data/mongo-volume:/data/db
    restart: always
    expose:
      - 27017

  ui:
    build:
      context: ../../src/ui
    image: ainotebook-ui:latest
    expose:
      - 80
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ../../src/server
    image: ainotebook-backend:latest
    depends_on:
      - mongo
    expose:
      - 5000
    restart: always
    command: [ "python3", "server.py" ]

  proxy:
    image: nginx:latest
    depends_on:
      - backend
    volumes:
      - ./ainotebook-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
