version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ../../data/mongo-volume:/data/db
    restart: always
    ports:
      - 8000:27017

  ui:
    container_name: ui
    build:
      context: ../../src/frontend-service
    image: ainotebook-ui:tag
    ports:
      - 8080:80
    restart: always

  server:
    container_name: server
    build:
      context: ../../src/server
    image: ainotebook-server:tag
    ports:
      - 8001:5000
    restart: always
    command: [ "python3", "server.py" ]

  proxy:
    container_name: ainotebook-proxy
    image: nginx:latest
    depends_on:
      - server
      - ui
    volumes:
      - ./ainotebook-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80