version: '3'

services:
  mongo:
    container_name: mongo-service
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ../../data/mongo-volume:/data/db
    restart: always
    ports:
    - 8000:27017

  frontend:
    container_name: frontend-service
    build:
      context: ../../src/frontend-service
    image: frontend-service:tag
    ports:
    - 8001:80
    restart: always